import os

# Groq API Configuration
GROQ_API_KEY = "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"

# Snowflake Configuration
SNOWFLAKE_USER = "RAJU"
SNOWFLAKE_PASSWORD = "RAJUsridevi1234"
SNOWFLAKE_ACCOUNT = "JNXKWEC-OX72808"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "DB1"
SNOWFLAKE_SCHEMA = "PRODUCT_SCHEMA"
